services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context:  requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
     - mariadb:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure


  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    ports: 
      - "9000:9000"

  redis:
    container_name: redis
    env_file: .env
    volumes:
      - redis:/var/lib/redis
    networks:
      - inception
    build: 
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    restart: on-failure
    ports: 
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "set", "healthcheak", "1"]
      interval: 5s
      timeout: 3s
      retries: 5

  ftp:
    container_name: ftp
    build: 
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: on-failure
    depends_on:
      - wordpress

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/caburges/data/mariadb'

  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/caburges/data/wordpress'

  redis:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/caburges/data/redis'
 
networks:
  inception:
    driver: bridge
